apiVersion: operator.aquasec.com/v1alpha1
kind: AquaEnforcer
metadata:
  name: aqua
spec:
  infra:
    serviceAccount: "aqua-sa"
    version: "2022.4"
  gateway:
    host: aqua-gateway
    port: 8443
  token: "token"
  aqua_express_mode: false                  # Optional: Change to true, to enable express mode deployment of enforcer