apiVersion: operator.aquasec.com/v1alpha1
kind: AquaKubeEnforcer
metadata:
  name: aquakubeenforcer
spec:
  infra:
    version: '2022.4'
    serviceAccount: aqua-kube-enforcer-sa
  config:
    gateway_address: 'aqua-gateway:8443'
    cluster_name: Default-cluster-name
    imagePullSecret: aqua-registry
  deploy:
    service: ClusterIP
    image:
      registry: registry.aquasec.com
      tag: <<KUBE_ENFORCER_TAG>>
      repository: kube-enforcer
      pullPolicy: Always
  token: <<KUBE_ENFORCER_GROUP_TOKEN>>
  starboard:
    allowAnyVersion: true
    infra:
      version: 0.14.1
      serviceAccount: starboard-operator
    config:
      imagePullSecret: starboard-registry
    deploy:
      replicas: 1
      image:
        registry: docker.io/aquasec
        tag: ''
        repository: starboard-operator
        pullPolicy: IfNotPresent
