apiVersion: operator.aquasec.com/v1alpha1
kind: AquaDatabase
metadata:
  name: aqua
spec:
  infra:
    serviceAccount: "aqua-sa"
    namespace: "aqua"
    version: "2022.4"
    platform: "openshift"
  deploy:
    replicas: 1
    service: "ClusterIP"
  diskSize: 10